
---
# Restart the Nagios NRPE Agent
# Since RedHat based OS's and Debian based ones call the service
# different names, we use a variable set in vars/{{ ansible_os_family }}.yml


- name: restart nagios-nrpe-agent
  service: name="{{ nagios_nrpe_server_service }}" state=restarted