---
# Nagios NRPE Agent installation

# Include OS-specific variables general
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"


# Include OS-architecture-specific variables
- name: Include RedHat x86 variables
  include_vars: "{{ ansible_os_family }}-x86.yml"
  when: "'{{ ansible_os_family }}' == 'RedHat' and '{{ ansible_architecture }}' == 'i386'"


- name: Include RedHat x64 variables
  include_vars: "{{ ansible_os_family }}-x64.yml"
  when: "'{{ ansible_os_family }}' == 'RedHat' and '{{ ansible_architecture }}' == 'x86_64'"


# Install our needed packages for each specific OS
# REdHat based packages
- include: packages_redhat.yml
  when: "'{{ ansible_os_family }}' == 'RedHat'"


# Create main config fro agent
- name: Create nrpe.cfg from tempalte
  template: >
    src="nrpe.cfg.j2"
    dest="{{ nagios_nrpe_server_dir }}/nrpe.cfg"
    owner=root group=root mode=0644
  notify: restart nagios-nrpe-agent


# Create nrpe_base_checks.cfg
- name: Create nrpe_base_checks.cfg from template
  template: >
    src="nrpe_base_checks.cfg.j2"
    dest="{{ nagios_nrpe_server_dir }}/nrpe_base_checks.cfg"
    owner=root group=root mode=0644
  notify: restart nagios-nrpe-agent


# Sync our plugins
- name: Install global plugins
  copy: >
    src="{{ item }}"
    dest="{{ nagios_nrpe_server_plugins_dir }}/"
    owner=root group=root mode=0755
  with_fileglob:
    - plugins/global/*


# Install per-server plugins
- name: Install per-server plugins
  copy: >
    src="{{ item }}"
    dest="{{ nagios_nrpe_server_plugins_dir }}/"
    owner=root group=root mode=0755
  with_fileglob:
    - "plugins/{{ ansible_fqdn }}/*"


# Ensure NRPE Agent is running and will start at boot
- name: Ensure NRPE Agent is running
  service: name="{{ nagios_nrpe_server_service }}" state=started enabled=yes