---


- include: wpl2/application_push_apps_bashrc.yml


- include: wpl2/application_push_configs.yml


- include: wpl2/application_push_cluster_workaround_script.yml


- include: wpl2/application_restart_tomcat.yml
