---


# build.properties

- meta: flush_handlers
  tags: ["push_all", "push_configs", "push_build_prp_conf"]


- name: including build.properties.yml variables for wpl2
  include_vars: ../../vars/wpl_hosts/{{ inventory_hostname }}/application/build.properties.yml
  tags: ["push_all", "push_configs", "push_build_prp_conf"]


- name: generating build.properties
  template:
    src=../../templates/wpl2/build.properties.j2
    dest=/111//product-data/conf/current/build.properties
    owner=apps
    group=java
    mode=0755
    backup=yes
  register: current_obj
  notify:
    - ensure backup dir is created
    - backup config
  tags: ["push_all", "push_configs", "push_build_prp_conf"]


#- name: test test
#  debug: var="{{ current_obj }}"
#  tags: ["push_all", "push_configs", "push_build_prp_conf"]


# application-ext.properties

- meta: flush_handlers
  tags: ["push_all", "push_configs", "push_application_ext_prp_conf"]


- name: including application-ext.properties.yml variables for wpl2
  include_vars: ../../vars/wpl_hosts/{{ inventory_hostname }}/application/application-ext.properties.yml
  tags: ["push_all", "push_configs", "push_application_ext_prp_conf"]


- name: generating application-ext.properties
  template:
    src=../../templates/wpl2/application-ext.properties.j2
    dest=/111//product-data/conf/current/app-application-6.1.1-ce-ga2/application-ext.properties
    owner=apps
    group=java
    mode=0755
    backup=yes
  register: current_obj
  notify:
    - ensure backup dir is created
    - backup config
  tags: ["push_all", "push_configs", "push_application_ext_prp_conf"]


# jks_t.keystore

- meta: flush_handlers
  tags: ["push_all", "push_configs", "push_keystore", "push_trust_keystore"]


- name: pushing jks_t.keystore
  copy:
    src=../../vars/wpl_hosts/{{ inventory_hostname }}/keystore/jks_t.keystore
    dest=/111//product-data/conf/current/keys/jks_t.keystore
    owner=apps
    group=java
    mode=0640
    backup=yes
  register: current_obj
  notify:
    - ensure backup dir is created
    - backup config
  tags: ["push_all", "push_configs", "push_keystore", "push_trust_keystore"]


# jks_k.keystore

- meta: flush_handlers
  tags: ["push_all", "push_configs", "push_keystore", "push_keys_keystore"]


- name: pushing jks_k.keystore
  copy:
    src=../../vars/wpl_hosts/{{ inventory_hostname }}/keystore/jks_k.keystore
    dest=/111//product-data/conf/current/keys/jks_k.keystore
    owner=apps
    group=java
    mode=0640
    backup=yes
  register: current_obj
  notify:
    - ensure backup dir is created
    - backup config
  tags: ["push_all", "push_configs", "push_keystore", "push_keys_keystore"]


# log4j.xml

- meta: flush_handlers
  tags: ["push_all", "push_configs", "push_log4j"]
  when: log4j == 'present'


- name: pushing log4j.xml
  copy:
    src=../../files/application/stuff/log4j.xml
    dest=/111//product-data/package/launcher/log4j.xml
    owner=apps
    group=java
    mode=0640
    backup=yes
  register: current_obj
  notify:
    - ensure backup dir is created
    - backup config
  tags: ["push_all", "push_configs", "push_log4j"]
  when: log4j == 'present'


- meta: flush_handlers
  tags: ["push_all", "push_configs", "push_log4j"]
  when: log4j == 'present'


- name: pushing log4j-extras.jar
  copy:
    src=../../files/application/stuff/log4j-extras.jar
    dest=/111//product-data/package/launcher/lib/log4j-extras.jar
    owner=apps
    group=java
    mode=0640
    backup=no
  register: current_obj
  tags: ["push_all", "push_configs", "push_log4j"]
  when: log4j == 'present'


#- name: REPLACE string in build.xml
#  lineinfile:
#    dest="/111//product-data/package/build.xml"
#    state=present
#    regexp='^(.*)dir="${launcher.dir}" classpath="${launcher.classes.dir}:${launcher.lib.dir}/log4j-1.2.16.jar:(.*)$'
#    line='\1dir="${launcher.dir}" classpath="${launcher.classes.dir}:${launcher.lib.dir}/log4j-1.2.16.jar:${launcher.lib.dir}/log4j-extras.jar:\2'
#    backup=no
#    backrefs=yes
#  tags: ["push_all", "push_configs", "push_log4j"]
#  when: " '{{log4j_file}}' == 'present' "


#- name: REPLACE string in build.xml
#  replace:
#    dest="/111//product-data/package/build.xml"
#    regexp='^(.*)dir="${launcher.dir}" classpath="${launcher.classes.dir}:${launcher.lib.dir}/log4j-1.2.16.jar:(.*)$'
#    replace='\1dir="${launcher.dir}" classpath="${launcher.classes.dir}:${launcher.lib.dir}/log4j-1.2.16.jar:${launcher.lib.dir}/log4j-extras.jar:\2'
#    backup=no
#  tags: ["push_all", "push_configs", "push_log4j"]
#  when: " '{{log4j_file}}' == 'present' "