---


- meta: flush_handlers
  tags: ["push_all", "push_apps_bashrc"]


- name: generating apps's .bashrc
  template: src="../../templates/wpl2/apps_bashrc.j2"
            dest="/111//.bashrc"
            owner=apps
            group=java
            mode=0644
  tags: ["push_all", "push_apps_bashrc"]