---
nagios_nrpe_server_bind_address: "*"
nagios_nrpe_server_port: 5001
nagios_nrpe_server_allowed_hosts: "127.0.0.1,1.1.1.1"
nagios_nrpe_server_dont_blame_nrpe: 1
#should match "-t 60" in commands.cfg on nagios server side
nagios_nrpe_server_command_timeout: 60